#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-deployment-job-ondemandprocessingdemo
spec:
  template:
    spec:
      containers:
      - name: prefect-deployment-job
        image: prefecthq/prefect:3.2.13-python3.11-kubernetes
        command:
          - bash
          - -c
          - |
            set -e # exit in case of error
            echo "📦 Cloning the repository..."
            git clone --branch develop https://github.com/RS-PYTHON/rs-client-libraries.git /tmp/rs-client-libraries

            echo "📂 Check the rs_workflow folder contents:"
            ls /tmp/rs-client-libraries/rs_workflows || echo "⚠️ Folder rs_workflows not found"

            echo "🚀 Déploiement Prefect..."
            cd /tmp/rs-client-libraries
            #git log -1
            prefect --no-prompt  deploy --prefect-file /app/prefect.yaml --all;
        env:
        - name: PREFECT_API_URL
          value: "http://prefect-server.processing.svc.cluster.local:4200/api"
        volumeMounts:
        - name: deployment-script
          mountPath: /app
      volumes:
      - name: deployment-script
        configMap:
          name: prefect-flow-deploy-config-ondemandprocessingdemo
      restartPolicy: Never
