# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: prefect-flow-deploy-config-{{ app_name }}
data:
  prefect.yaml: |
    prefect-version: "3"

    pull:
    - prefect.deployments.steps.git_clone:
        repository: https://github.com/RS-PYTHON/rs-client-libraries.git
        branch: develop  # v1.0a8

    definitions:
      work_pools:
        my_work_pool: &my_work_pool
          name: {{ prefect3worker.eopf.name }}

    deployments:
    - name: On-demand processing
      tags: ["on-demand", "processing"]
      entrypoint: ./rs_workflows/on_demand_processing.py:dpr_processing
      work_pool: *my_work_pool
    - name: On-demand L0 processing
      tags: ["on-demand", "processing"]
      entrypoint: ./rs_workflows/on_demand/common/l0.py:process_l0
      work_pool: *my_work_pool
    - name: On-demand S1L0 processing
      tags: ["on-demand", "processing"]
      entrypoint: ./rs_workflows/on_demand/sentinel1/s1_l0.py:process_s1l0
      work_pool: *my_work_pool
    - name: On-demand S3L0 processing
      tags: ["on-demand", "processing"]
      entrypoint: ./rs_workflows/on_demand/sentinel3/s3_l0.py:process_s3l0
      work_pool: *my_work_pool
