#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-deployment-job-{{ app_name }}
spec:
  template:
    spec:
      containers:
      - name: prefect-deployment-job
        image: prefecthq/prefect:3.6.12-python3.13-kubernetes
        command:
          - bash
          - -c
          - |
            set -e
            echo "📦 Cloning the repository..."
            git clone --branch develop https://github.com/RS-PYTHON/rs-client-libraries.git

            echo "📂 Check the rs_workflow folder contents:"
            ls /opt/prefect/rs-client-libraries/rs_workflows || echo "⚠️ Folder rs_workflows not found"

            echo "Copying the prefect deployment file into /opt/prefect/rs-client-libraries/rs_workflows"
            cp /opt/prefect/prefect.yaml /opt/prefect/rs-client-libraries/prefect.yaml

            echo "Installing rs-client-libraries"
            uv pip install rs-client-libraries==1.0a6

            echo "📦 Prefect deployment initalisation";
            echo "prefect --no-prompt deploy --all";
            prefect --no-prompt deploy --all;

            #sleep 3600
        env:
        - name: PREFECT_API_URL
          value: "http://prefect-server.processing.svc.cluster.local:4200/api"
        volumeMounts:
        - name: deployment-script
          mountPath: /opt/prefect/prefect.yaml
          subPath: prefect.yaml
      volumes:
      - name: deployment-script
        configMap:
          name: prefect-flow-deploy-config-{{ app_name }}
      restartPolicy: Never
