# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: prefect-flow-deploy-config-{{ app_name }}
data:
  prefect.yaml: |
    prefect-version: "3"

    pull:
    - prefect.deployments.steps.git_clone:
        repository: https://github.com/RS-PYTHON/rs-client-libraries.git
        branch: v1.0a12

    definitions:
      work_pools:
        my_work_pool: &my_work_pool
          name: {{ prefect3worker.monitoring.name }}

    deployments:
    - name: Synchronize OSAM Accounts
      tags: ["operation", "osam"]
      entrypoint: ./rs_workflows/operation/osam_flows.py:osam_synchronize_accounts
      work_pool: *my_work_pool
    - name: Update OSAM Account
      tags: ["operation", "osam"]
      entrypoint: ./rs_workflows/operation/osam_flows.py:osam_update_user
      work_pool: *my_work_pool
    - name: Collect OBS Logs
      tags: ["operation", "obs"]
      entrypoint: ./rs_workflows/operation/quota_monitoring_flow.py:collect_obs_logs
      work_pool: *my_work_pool
    - name: Consolidate OBS Logs
      tags: ["operation", "obs"]
      entrypoint: ./rs_workflows/operation/quota_monitoring_flow.py:consolidate_obs_logs
      work_pool: *my_work_pool
    - name: Clean old prefect workers
      tags: ["operation", "prefect"]
      entrypoint: ./rs_workflows/operation/clean_old_prefect_workers_flow.py:cleanup_offline_workers
      work_pool: *my_work_pool
      parameters:
        work_pools_csv: "monitoring-k8s-pool,processing-integrated-k8s-pool,processing-sandbox-k8s-pool"
        max_age_days: 1
      schedules:
        - cron: "0 10 * * *"
          timezone: "Europe/Paris"
          active: true
