# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Ansible playbook deployment

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
  workflow_dispatch: # manual trigger
    inputs:
      infra_core_ref:
        description: rs-infra-core branch or tag
        required: true
        default: 'develop'
      client_libraries_ref:
        description: rs-client-libraries branch or tag
        required: true
        default: 'develop'
      workflow_env_ref:
        description: rs-workflow-env branch or tag
        required: true
        default: 'develop'
jobs:
  test-deploy:
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#          - name: "Deployment with monitoring"
#            deploy_monitoring: true
          - name: "Deployment without monitoring"
            deploy_monitoring: false
    steps:
      - name: Check if branches exist in rs-infra-core and rs-client-libraries
        id: check_branches
        env:
          LOCAL_BRANCH: ${{ github.head_ref }}
          INFRA_CORE_REF: ${{ inputs.infra_core_ref || '' }}
          CLIENT_LIBRARIES_REF: ${{ inputs.client_libraries_ref || '' }}
          WORKFLOW_ENV_REF: ${{ inputs.workflow_env_ref || '' }}
        run: |
          BRANCH="${INFRA_CORE_REF:-$LOCAL_BRANCH}"
          if git ls-remote --heads https://github.com/RS-PYTHON/rs-infra-core.git $BRANCH | grep -q $BRANCH; then
            echo "infra_branch_to_use=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "infra_branch_to_use=" >> $GITHUB_OUTPUT  # Leave empty to use default
          fi
          BRANCH="${CLIENT_LIBRARIES_REF:-$LOCAL_BRANCH}"
          if git ls-remote --heads https://github.com/RS-PYTHON/rs-client-libraries.git $BRANCH | grep -q $BRANCH; then
            echo "client_branch_to_use=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "client_branch_to_use=" >> $GITHUB_OUTPUT  # Leave empty to use default
          fi
          BRANCH="${WORKFLOW_ENV_REF:-$LOCAL_BRANCH}"
          if git ls-remote --heads https://github.com/RS-PYTHON/rs-workflow-env.git $BRANCH | grep -q $BRANCH; then
            echo "workflow_env_branch_to_use=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "workflow_env_branch_to_use=" >> $GITHUB_OUTPUT  # Leave empty to use default
          fi
      - name: Checkout infra-core repository
        uses: actions/checkout@v6
        with:
          repository: RS-PYTHON/rs-infra-core
          ref: ${{ steps.check_branches.outputs.infra_branch_to_use }}
      - name: Checkout infra-monitoring repository
        uses: actions/checkout@v6
        if: ${{ matrix.deploy_monitoring }}
        with:
          path: rs-infra-monitoring
          repository: RS-PYTHON/rs-infra-monitoring
      - name: Checkout workflow-env repository
        uses: actions/checkout@v6
        with:
          repository: RS-PYTHON/rs-workflow-env
          ref: ${{ steps.check_branches.outputs.workflow_env_branch_to_use }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: rs-workflow-deployment
          ref: ${{ github.ref }}
      - name: Set workflows version
        run: |
          BRANCH="${{ steps.check_branches.outputs.client_branch_to_use }}"

          if [ -z "$BRANCH" ]; then
            echo "No branch override provided, skipping update."
            exit 0
          fi

          echo "Using rs-client-libraries branch: $BRANCH"

          find rs-workflow-deployment/apps -type f -name "configmap.yaml" | while read file; do
            echo "Updating $file"
            sed -i -E "s|^[[:space:]]*branch:[[:space:]]*.*$|        branch: $BRANCH|" "$file"
          done
          find rs-workflow-deployment/apps -type f -name "job.yaml" | while read file; do
            echo "Updating $file"
            sed -i -E "s|^[[:space:]]*value:[[:space:]]*develop.*$|          value: $BRANCH|" "$file"
          done
      - name: Aggressive cleanup
        run: |
          # Cleanup disk space (level between 0 and 14, more cleaning takes more time)
          .github/common/resources/aggressive-cleanup.sh 6
      - name: Install requirements
        run: .github/common/resources/install-requirements.sh
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        with:
          addons: 'metallb,metrics-server'
          cpus: 4
          memory: 8000m
          start-args: '--disk-size=32g'
      - name: "Configure cluster labels, IP and DNS (host + CoreDNS)"
        run: |
          if [ "${{ matrix.deploy_monitoring }}" = "true" ]; then
            SUBDOMAINS="dash-dask iam kube monitoring oauth2-proxy processing"
          else
            SUBDOMAINS="dash-dask iam kube oauth2-proxy processing"
          fi
          .github/common/resources/configure-cluster.sh \
            "node-role.kubernetes.io/infra= node-role.kubernetes.io/rs_env= node-role.kubernetes.io/prefect_flow= node-role.kubernetes.io/access_csc=" \
            "$SUBDOMAINS"
      - name: Deploy seaweedfs
        run: |
          if [ "${{ matrix.deploy_monitoring }}" = "true" ]; then
            MINIO_BUCKETS="rs-cluster-psql,rs-cluster-velero,rs-cluster-loki-chunks,rs-cluster-loki-ruler,rs-cluster-tempo"
          else
            MINIO_BUCKETS="rs-cluster-psql,rs-cluster-velero"
          fi
          .github/common/resources/deploy-seaweedfs.sh $MINIO_BUCKETS
      - name: Generate inventory
        run: |
          .github/common/resources/configure-inventory.sh
          # --- Generate inventory
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook registry.yaml -i inventory/mycluster/hosts.yaml -e ci_mode=true
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook generate_inventory.yaml -i inventory/mycluster/hosts.yaml
      - name: Deploy the core apps (for real)
        run: |
          # --- Use local cluster issuer instead of Let's Encrypt
          if [ "${{ matrix.deploy_monitoring }}" = "true" ]; then
            .github/common/resources/configure-local-ca.sh \
              dash-dask:dask-gateway iam:iam kube:default monitoring:monitoring processing:processing oauth2-proxy:iam
          else
            .github/common/resources/configure-local-ca.sh \
              dash-dask:dask-gateway iam:iam kube:default processing:processing oauth2-proxy:iam
          fi
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml
      - name: Deploy the monitoring apps (for real)
        if: ${{ matrix.deploy_monitoring }}
        run: |
          ./rs-infra-monitoring/.github/common/resources/configure-minikube-deployment.sh
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-infra-monitoring/apps/"]}'
      - name: Deploy the required workflow-env apps (for real)
        run: |
          ./rs-workflow-env/.github/common/resources/configure-minikube-deployment.sh
          # we only need Prefect
          for app in prefect3-db prefect3-server prefect3-worker-sandbox prefect3-worker-integrated prefect3-worker-monitoring ; do
            echo Installing $app...
            conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml  -e '{"package_paths": ["./rs-workflow-env/apps/"], "app": "'$app'"}'
          done
      - name: Deploy the workflow-deployment apps (check)
        run: |
          conda run -n rspy ansible-playbook --check apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-workflow-deployment/apps/"]}'
      - name: Deploy the workflow-deployment apps (for real)
        run: |
          sed -i 's!debug: false!debug: true!g' roles/app-installer/defaults/main.yaml
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-workflow-deployment/apps/"]}' -e job_wait_timeout=360
      - name: 🩺 Kubernetes failure diagnostics
        if: failure()
        run: .github/common/resources/minikube-diagnostics.sh
